PRN231_ProjectQA_MVC/PRN231_ProjectQA_MVC/Controllers/UserMController.cs
using Microsoft.AspNetCore.Mvc;
using PRN231_ProjectQA_MVC.Models.User;
using PRN231_ProjectQA_MVC.Models;
using System.Diagnostics;
using System.Text.Json;
using PRN231_ProjectQA_MVC.Authorizations;

namespace PRN231_ProjectQA_MVC.Controllers
{
    public class UserMController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;

        public UserMController(IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _httpClient = httpClientFactory.CreateClient("MyHttpClient");
            _apiBaseUrl = configuration["ApiSettings:BaseUrl"];
            _httpClient.BaseAddress = new Uri(_apiBaseUrl);
        }
       
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> Index(int? page, string searchString = null, string roleFilter = null, string statusFilter = null)
        {
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 10;
            List<UserModel> users = new List<UserModel>();

            HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/User");


            if (response.IsSuccessStatusCode)
            {
                string jsonString = response.Content.ReadAsStringAsync().Result;

                //convert from json to model
                users = JsonSerializer.Deserialize<List<UserModel>>
                    (jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            }
            else
            {
                users = new List<UserModel>(); // Or handle errors another way
            }
            // Search
            if (!string.IsNullOrEmpty(searchString))
            {
                users = users.Where(u => u.Username.Contains(searchString, StringComparison.OrdinalIgnoreCase) ||
                                         u.Email.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            // Filter by Role
            if (!string.IsNullOrEmpty(roleFilter))
            {
                users = users.Where(u => u.RoleName.Equals(roleFilter, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            // Filter by Status
            if (!string.IsNullOrEmpty(statusFilter))
            {
                users = users.Where(u => u.Status.Equals(statusFilter, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            ViewBag.pageLength = (users.Count - 1) / pageSize + 1;
            users = users.Skip((int)((page - 1) * pageSize)).Take(pageSize).ToList();

            ViewBag.page = page;
            ViewBag.roleFilter = roleFilter;
            ViewBag.statusFilter = statusFilter;
            ViewBag.searchString = searchString;
            // Pass the data to the view
            return View(users);
        }

        [HttpGet]
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> Edit(Guid id)
        {
            UserModel user = new UserModel();
            if (TempData["UserData"] != null)
            {

                user = TempData["UserData"] as UserModel;
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
            }
            else
            {

                HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/User/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string jsonString = await response.Content.ReadAsStringAsync();
                    string a = jsonString;
                    user = JsonSerializer.Deserialize<UserModel>(
                        jsonString,
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                    );
                }

                else
                {
                    user = new UserModel(); // Or handle errors another way
                }
            }

            return View(user);
        }
        [HttpGet]
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> Create(Guid id)
        {
            return View();
        }

        [HttpPost]
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> Update(Guid id, string UserName, string Email, DateTime Dob, string Role)
        {
            var userModel = new UpdateUserModel
            {
                Username = UserName,
                Email = Email,
               
                RoleName = Role
            };

            try
            {
                var apiUrl = $"{_httpClient.BaseAddress}/User/{id}";
                var response = await _httpClient.PutAsJsonAsync(apiUrl, userModel);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Edit", new { id = id });
                }
                else
                {

                    var errorContent = await response.Content.ReadAsStringAsync();
                    TempData["ErrorMessage"] = $"Lỗi từ API: {errorContent}";
                    Console.WriteLine($"API call failed. Status code: {response.StatusCode}, Error: {errorContent}");

                    return RedirectToAction("Edit", new { id = id });
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Lỗi hệ thống: {ex.Message}";
                TempData["UserData"] = userModel;
                return RedirectToAction("Edit", new { id = id });
            }
        }


        [HttpPost]
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> ChangeStatus(Guid id, string status)
        {
            //Convert status to int
            status = status.Equals("Active", StringComparison.OrdinalIgnoreCase) ? "0" : "1";

            //Set URL
            var apiUrl = $"{_httpClient.BaseAddress}/User/{id}/{status}";

            //Call API
            HttpResponseMessage response = await _httpClient.PutAsync(apiUrl, null);


            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Edit", new { id = id });
            }
            else
            {

                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        [AuthorizeRole("Admin")]
        public async Task<IActionResult> Add(AddUserModel addUserModel)
        {


            if (!ModelState.IsValid)
            {

                return View(addUserModel);
            }

            try
            {
                //Call API
                var apiUrl = $"{_httpClient.BaseAddress}/User";
                HttpResponseMessage response = await _httpClient.PostAsJsonAsync(apiUrl, addUserModel);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    var errorContent = await response.Content.ReadAsStringAsync();

                    ModelState.AddModelError(string.Empty, $"Có lỗi xảy ra khi thêm người dùng. Mã lỗi: {response.StatusCode}. Chi tiết: {errorContent}");
                    return RedirectToAction("Create");

                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, "Lỗi hệ thống: " + ex.Message);
                return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }

    }
}

PRN231_ProjectQA_MVC/PRN231_ProjectQA_MVC/Views/UserM/Create.cshtml
@model PRN231_ProjectQA_MVC.Models.User.AddUserModel
@{
    ViewData["Title"] = "User Management";
    var currentSort = ViewBag.sortOrder as string;
    var searchString = ViewBag.searchString as string;
    var roleFilter = ViewBag.roleFilter as string;
    var statusFilter = ViewBag.statusFilter as string;
}
<style>


    .custom-blue-btn {
        background-color: #007bff; /* Replace with your desired blue color */
        color: white; /* Text color */
        border: none; /* Remove border */
        margin-left: 500px;
        margin-top: 50px; /* Add some padding */
    }

        .custom-blue-btn:hover {
            background-color: #0056b3; /* Darker shade on hover */
        }

</style>
<body>
    <div class="app">
        <div class="header" id="header">
            <div class="navbar fixed-top" id="navbar">
                <div class="shelter">
                    <a class="navbar__nav nav__logo nav__underline" href="index.html">
                        <span class="link-title">
                            <i class="fa fa-mars"></i>
                            <span>K</span>ommunity
                        </span>
                    </a>
                    <div class="navbar__nav navbar__nav-toggle">
                        <i class="fa fa-bars"></i>
                    </div>
                    <nav class="nav__items">
                        <div class="navbar__nav nav__underline">
                            <a href="@Url.Action("Index", "Home")" class="nav__link">
                                Home
                            </a>

                        </div>
                        <div class="navbar__nav nav__underline">
                            <a href="@Url.Action("Index", "Post")" class="nav__link active">
                                Answer
                            </a>

                        </div>
                        <form method="get">
                            <div class="navbar__nav nav__underline p__8">
                                <div class="search">
                                    <input class="form-control" type="text" name="searchString" value="@ViewBag.searchString" placeholder="Search for Questions">
                                </div>
                            </div>

                        </form>

                        <div class="navbar__nav nav__underline p__8">
                            <a href="@Url.Action("Ask", "Post")">  <button type="button" class="btn btn-blue ripple" id="modalBtn">Ask a Question <i class="fa fa-plus"></i></button></a>
                        </div>
                    </nav>
                    @if (Context.Request.Cookies["AuthToken"] != null)
                    {
                        var profileImageEncoded = Context.Request.Cookies["Img"];
                        var profileImage = !string.IsNullOrEmpty(profileImageEncoded) ?
                        Uri.UnescapeDataString(profileImageEncoded) :
                        "./assets/images/boy.png";

                        <nav class="nav__items nav__items-right">
                            <div class="navbar__nav pr-0 p__8 dropdown">
                                <a href="#"><img src="@profileImage" class="avatar-sm" title="Profile"></a>
                                <div class="dropdown-content">
                                    <a href="@Url.Action("Logout", "Auth")">Log out <i class="fa fa-power-off"></i></a>
                                    <a href="@Url.Action("Index", "Profile")">
                                        Profile <i class="fa fa-user-o"></i>

                                    </a>
                                </div>
                            </div>
                        </nav>
                    }

                </div><!--end container-->
            </div><!--end navbar-->
        </div><!--end header-->
        <section class="py-3">
            <div class="shelter">
                <div class="ddd">
                    <div class="columns">
                        <div class="col-2">
                            <div class="left-side">
                                <h1>Activity</h1>
                                <div class="left-side__item active2">
                                    <a class="side-link" href="@Url.Action("Index", "UserM")"><span class="pr-1"><i class="fa fa-user"></i></span> User Management</a>
                                </div>
                                <div class="left-side__item">
                                    <a class="side-link" href="@Url.Action("Index", "Post")"><span class="pr-1"><i class="fa fa-book"></i></span> Post Management</a>
                                </div>


                            </div>
                        </div>
                        <div class="col-7" style="padding-top:100px;">
                            <form asp-action="Add" method="post" onsubmit="return confirm('Are you sure you want to create ?');">
                                <div class="validation-summary">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                </div>
                                <div class="row">
                                    <div class="col-md-6">

                                        <div class="form-group">
                                            <label asp-for="Username" ></label>
                                            <input name="UserName" class="form-control" />
                                            <span asp-validation-for="Username" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Email" ></label>
                                            <input name="Email" class="form-control" />
                                            <span asp-validation-for="Email" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Password" ></label>
                                            <input name="Password" class="form-control" />
                                            <span asp-validation-for="Password" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                      
                                        <div class="form-group">
                                            <label asp-for="RoleName" ></label>
                                            <select name="RoleName" class="form-control">
                                                <option value="Admin">Admin</option>
                                                <option value="User">User</option>
                                                <option value="Manager">Manager</option>
                                            </select>
                                            <span asp-validation-for="RoleName" class="text-danger"></span>
                                        </div>

                                    </div>
                                </div>
                                <button type="submit" class="btn custom-blue-btn">Create</button>
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </section>

    </div>


</body>
</html>

PRN231_ProjectQA_MVC/PRN231_ProjectQA_MVC/Views/UserM/Edit.cshtml
@model PRN231_ProjectQA_MVC.Models.User.UserModel
@{
    ViewData["Title"] = "User Management";
    var currentSort = ViewBag.sortOrder as string;
    var searchString = ViewBag.searchString as string;
    var roleFilter = ViewBag.roleFilter as string;
    var statusFilter = ViewBag.statusFilter as string;
}
<style>


    .custom-blue-btn {
        background-color: #007bff; /* Replace with your desired blue color */
        color: white; /* Text color */
        border: none; /* Remove border */
        margin-left:500px;
        margin-top:50px; /* Add some padding */
    }

        .custom-blue-btn:hover {
            background-color: #0056b3; /* Darker shade on hover */
        }

</style>
<body>
    <div class="app">
        <div class="header" id="header">
            <div class="navbar fixed-top" id="navbar">
                <div class="shelter">
                    <a class="navbar__nav nav__logo nav__underline" href="index.html">
                        <span class="link-title">
                            <i class="fa fa-mars"></i>
                            <span>K</span>ommunity
                        </span>
                    </a>
                    <div class="navbar__nav navbar__nav-toggle">
                        <i class="fa fa-bars"></i>
                    </div>
                    <nav class="nav__items">
                        <div class="navbar__nav nav__underline">
                            <a href="@Url.Action("Index", "Home")" class="nav__link">
                                Home
                            </a>

                        </div>
                        <div class="navbar__nav nav__underline">
                            <a href="@Url.Action("Index", "Post")" class="nav__link active">
                                Answer
                            </a>

                        </div>
                        <form method="get">
                            <div class="navbar__nav nav__underline p__8">
                                <div class="search">
                                    <input class="form-control" type="text" name="searchString" value="@ViewBag.searchString" placeholder="Search for Questions">
                                </div>
                            </div>

                        </form>

                        <div class="navbar__nav nav__underline p__8">
                            <a href="@Url.Action("Ask", "Post")">  <button type="button" class="btn btn-blue ripple" id="modalBtn">Ask a Question <i class="fa fa-plus"></i></button></a>
                        </div>
                    </nav>
                    @if (Context.Request.Cookies["AuthToken"] != null)
                    {
                        var profileImageEncoded = Context.Request.Cookies["Img"];
                        var profileImage = !string.IsNullOrEmpty(profileImageEncoded) ?
                        Uri.UnescapeDataString(profileImageEncoded) :
                        "./assets/images/boy.png";

                        <nav class="nav__items nav__items-right">
                            <div class="navbar__nav pr-0 p__8 dropdown">
                                <a href="#"><img src="@profileImage" class="avatar-sm" title="Profile"></a>
                                <div class="dropdown-content">
                                    <a href="@Url.Action("Logout", "Auth")">Log out <i class="fa fa-power-off"></i></a>
                                    <a href="@Url.Action("Index", "Profile")">
                                        Profile <i class="fa fa-user-o"></i>

                                    </a>
                                </div>
                            </div>
                        </nav>
                    }
                    
                </div><!--end container-->
            </div><!--end navbar-->
        </div><!--end header-->
        <section class="py-3">
            <div class="shelter">
                <div class="ddd">
                    <div class="columns">
                        <div class="col-2">
                            <div class="left-side">
                                <h1>Activity</h1>
                                <div class="left-side__item active2">
                                    <a class="side-link" href="@Url.Action("Index", "UserM")"><span class="pr-1"><i class="fa fa-user"></i></span> User Management</a>
                                </div>
                                <div class="left-side__item">
                                    <a class="side-link" href="@Url.Action("Index", "Post")"><span class="pr-1"><i class="fa fa-book"></i></span> Post Management</a>
                                </div>


                            </div>
                        </div>
                        <div class="col-7">
                            <div class="col-12 d-flex justify-content-between align-items-center mb-3">
                                <h2>Edit User</h2>
                                <form asp-action="ChangeStatus" method="post" onsubmit="return confirm('Are you sure you want to change the status?');" class="d-inline">
                                    <input type="hidden" name="id" value="@Model.Id" />
                                    <input type="hidden" name="status" value="@Model.Status" />
                                    <div>
                                        <button type="submit" class="btn custom-blue-btn">Change Status</button>
                                    </div>
                                </form>

                            </div>

                            <form asp-action="Update" method="post" class="col-12" onsubmit="return confirm('Are you sure you want to save the changes?');">
                                <input type="hidden" name="Id" value="@Model.Id" />
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label >ID</label>
                                            <input name="Id" type="text" value="@Model.Id" class="form-control" readonly />
                                            
                                        </div>
                                        <div class="form-group">
                                            <label >User Name</label>
                                            <input name="UserName" type="text" value="@Model.Username" class="form-control" />
                                            <span class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input name="Email" type="text" value="@Model.Email" class="form-control" />
                                            
                                        </div>
                                      
                                    </div>

                                    <div class="col-md-6">
                                       
                                        <div class="form-group">
                                            <label>Role</label>
                                            @Html.DropDownList("Role", new List<SelectListItem>
                                            {
                                            new SelectListItem { Text = "Select a role", Value = "", Disabled = true, Selected = (Model.RoleName == null) },
                                            new SelectListItem { Text = "Admin", Value = "Admin", Selected = (Model.RoleName == "Admin") },
                                            new SelectListItem { Text = "Guest", Value = "Guest", Selected = (Model.RoleName == "Guest") },
                                            new SelectListItem { Text = "User", Value = "User", Selected = (Model.RoleName == "User") }
                                            }, new { @class = "form-control" })
                                            <span class="text-danger"></span>
                                            <span class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Status</label>
                                            <input name="Status" type="text" value="@Model.Status" class="form-control" readonly />
                                            <span class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn custom-blue-btn">Save</button>
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </section>
       
    </div>


</body>
</html>